const mongoose = require('mongoose');

const addressSchema = new mongoose.Schema({
  street: {
    type: String,
    required: true,
    trim: true,
  },
  city: {
    type: String,
    required: true,
    trim: true,
  },
  state: {
    type: String,
    required: true,
    trim: true,
  },
  zipCode: {
    type: String,
    required: true,
    trim: true,
  },
  country: {
    type: String,
    required: true,
    trim: true,
  },
}, { _id: false });

const orderItemSchema = new mongoose.Schema({
  productId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Product',
    required: true,
  },
  productName: {
    type: String,
    required: true,
  },
  quantity: {
    type: Number,
    required: true,
    min: [1, 'Quantity must be at least 1'],
  },
  unitPrice: {
    type: Number,
    required: true,
    min: [0, 'Unit price must be non-negative'],
  },
  subtotal: {
    type: Number,
    required: true,
    min: [0, 'Subtotal must be non-negative'],
  },
}, { _id: false });

const orderSchema = new mongoose.Schema({
  orderNumber: {
    type: String,
    required: false, // Generated by pre-save hook
    unique: true,
    index: true,
  },
  customerId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    sparse: true,
    index: true,
  },
  customerEmail: {
    type: String,
    required: [true, 'Customer email is required'],
    lowercase: true,
    trim: true,
    index: true,
  },
  customerFirstName: {
    type: String,
    required: false,
    trim: true,
  },
  customerLastName: {
    type: String,
    required: false,
    trim: true,
  },
  items: {
    type: [orderItemSchema],
    required: true,
    validate: {
      validator: function(v) {
        return v && v.length > 0;
      },
      message: 'Order must have at least one item',
    },
  },
  shippingAddress: {
    type: addressSchema,
    required: true,
  },
  billingAddress: {
    type: addressSchema,
    required: true,
  },
  paymentMethod: {
    type: String,
    enum: ['stripe', 'cash_on_delivery'],
    required: true,
  },
  paymentStatus: {
    type: String,
    enum: ['pending', 'processing', 'completed', 'failed', 'refunded'],
    default: 'pending',
    index: true,
  },
  paymentTransactionId: {
    type: String,
    sparse: true,
  },
  orderStatus: {
    type: String,
    enum: ['pending', 'processing', 'shipped', 'delivered', 'cancelled'],
    default: 'pending',
    index: true,
  },
  subtotal: {
    type: Number,
    required: true,
    min: [0, 'Subtotal must be non-negative'],
  },
  shippingCost: {
    type: Number,
    required: true,
    default: 0,
    min: [0, 'Shipping cost must be non-negative'],
  },
  total: {
    type: Number,
    required: true,
    min: [0, 'Total must be non-negative'],
  },
  shippedAt: {
    type: Date,
  },
  deliveredAt: {
    type: Date,
  },
  cancelledAt: {
    type: Date,
  },
}, {
  timestamps: true,
});

// Generate order number before saving
orderSchema.pre('save', async function() {
  if (!this.isNew || this.orderNumber) {
    return;
  }
  
  const year = new Date().getFullYear();
  const count = await mongoose.model('Order').countDocuments({});
  this.orderNumber = `ORD-${year}-${String(count + 1).padStart(6, '0')}`;
});

// Index on createdAt for sorting
orderSchema.index({ createdAt: -1 });

const Order = mongoose.model('Order', orderSchema);

module.exports = Order;

